import { CetasikaGroupTerms, CetasikaID } from "../model/interface";

export const cetasikaGroups = {
  sabbaSaddharana: [
    "phassa",
    "vedana",
    "sanna",
    "cetana",
    "ekaggata",
    "jivitindriya",
    "manasikara",
  ],
  pakinnaka: ["vitakka", "vicara", "adhimokha", "viriya", "piti", "chanda"],
  mohaCatukka: ["moha", "ahirika", "anottappa", "uddaccha"],
  lobhaTri: ["lobha", "ditthi", "mana"],
  dosaCatukka: ["dosa", "issa", "macchariya", "kukuccha"],
  thinamiddha: ["thina", "middha"],
  sobhanaSaddharana: [
    "saddha",
    "sati",
    "hiri",
    "ottappa",
    "alobha",
    "adosa",
    "tatramajjhattata",
    "cittapasadhi",
    "cittalahutta",
    "cittamudutta",
    "cittakammannata",
    "cittapagunnata",
    "cittujukata",
    "kayapasadhi",
    "kayalahutta",
    "kayamudutta",
    "kayakammannata",
    "kayapagunnata",
    "kayujukata",
  ],
  virati: ["sammavaca", "sammakammanta", "sammajiva"],
  appamanna: ["karuna", "mudita"],
} satisfies Record<CetasikaGroupTerms, CetasikaID[]>;
